title: Proposal to Final Report Writing Guide
description: A working guide to developing an IQP research proposal and final report.
url: https://roberts-andy.github.io
baseurl: /gitbook-test
markdown: kramdown
permalink: pretty
